### ISSUE TITLE
"Bad masonry element"

### ISSUE THREAD

**Issue by john-osullivan** [eiriklv/react-masonry-component#9]
Hi, I'm instantiating Masonry pretty similarly to how you have it in the example, except each child element is a React component.  For some reason, the dependent library outlayer throws an error "Bad masonry element".  After that, it repeatedly has a "Can't read property children of undefined" error.  Not sure what's going wrong here.

For some more context, I'm using React as the front-end with Meteor as the back-end.  Thoughts about where this could be coming from?

**Comment by eiriklv** [comment]
@john-osullivan Are you using the Meteor React package? What version of React is that? :-) Unfortunately I haven't played around much with Meteor and don't have any obvious clues to of what to look for.

**Comment by john-osullivan** [comment]
Yup, I'm using the Meteor React package. I believe it was recently upgraded to 0.14.1, specifically not to 0.14.2. That's what the devs said in an issue, I'll link out when I'm at my computer.
If it'd any additional trouble shooting help, it's a component I've defined myself using ES6 classes.-------- Original message --------From: "Eirik L. Vullum" <notifications@github.com> Date: 12/5/2015  07:30  (GMT-05:00) To: eiriklv/react-masonry-component <react-masonry-component@noreply.github.com> Cc: john-osullivan <johno@mit.edu> Subject: Re: [react-masonry-component] "Bad masonry element" (#9) 
@john-osullivan Are you using the Meteor React package? What version of React is that? :-) Unfortunately I haven't played around much with Meteor and don't have any obvious clues to of what to look for.

**Comment by migreva** [comment]
I was typing a response to this question just as [3.0.0](https://www.npmjs.com/package/react-masonry-component) was published! 

I think 3.0.0 fixes the issue, I think the problem might have been the ES6 import syntax I was using (which I assume @john-osullivan is using because he's using ES6 classes). 

The following way I was importing was throwing an error when using 2.0.0:

```
import React from 'react';
import Masonry 'react-masonry-component';
```

2.0.0 was the published npm module, and using that I needed to use the [2.0.0](https://github.com/eiriklv/react-masonry-component/tree/v2#usage) syntax of importing:

```
import React from 'react';
var Masonry = require('react-masonry-component')(React);
```

With 3.0.0,  I was able to use the following

```
import React from 'react';
import Masonry form 'react-masonry-component'
```

**Comment by afram** [comment]
@john-osullivan I would like to close this issue as it has been inactive for a while. Please reopen if you are still having issues :-)
